-- Você vai criar uma tabela para armazenar os dados de revistas (como por ex: Veja, Isto é, 
-- Epoca, Quatro Rodas, Claudia, etc).
-- Escreva e execute os comandos para:
-- • Criar a tabela chamada Revista para conter os campos: idRevista (int e chave 
-- primária da tabela), nome (varchar, tamanho 40), categoria (varchar, tamanho 30). Os 
-- valores de idRevista devem iniciar com o valor 1 e ser incrementado automaticamente 
-- pelo sistema.
-- • Inserir 4 registros na tabela, mas sem informar a categoria.
-- Escreva e execute os comandos para:
-- • Exibir todos os dados da tabela.
-- • Atualize os dados das categorias das 3 revistas inseridas. Exibir os dados da tabela 
-- novamente para verificar se atualizou corretamente.
-- • Insira mais 3 registros completos.
-- • Exibir novamente os dados da tabela.
-- • Exibir a descrição da estrutura da tabela.
-- • Alterar a tabela para que a coluna categoria possa ter no máximo 40 caracteres.
-- • Exibir novamente a descrição da estrutura da tabela, para verificar se alterou o 
-- tamanho da coluna categoria
-- • Acrescentar a coluna periodicidade à tabela, que é varchar(15).
-- • Exibir os dados da tabela.
-- • Excluir a coluna periodicidade da tabela.